configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/envgs.yaml # envgs model configuration
    - configs/datasets/renders_prnormals/shiny_office.yaml # dataset usage configuration

runner_cfg:
    epochs: 60

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
