configs:
    - configs/datasets/ref_real/ref_real.yaml

dataloader_cfg:
    dataset_cfg: &dataset_cfg
        ratio: 0.75
        data_root: data/datasets/renders_gt_ori/multichromeball_kitchen_v2/train
        view_sample: [0, null, 1]

val_dataloader_cfg:
    dataset_cfg:
        ratio: 0.75
        data_root: data/datasets/renders_gt_ori/multichromeball_kitchen_v2/test
        view_sample: [0, null, 1]

model_cfg:
    sampler_cfg:
        preload_gs: data/datasets/renders_gt_ori/multichromeball_kitchen_v2/train/sparse/0/points3D.ply
        spatial_scale: 0.6811219138459285
        # Environment Gaussian
        env_preload_gs: data/datasets/renders_gt_ori/multichromeball_kitchen_v2/train/envs/points3D.ply
        # env_bounds: [[-30.0, -30.0, -30.0], [30.0, 30.0, 30.0]]
        env_bounds: [[-0.35885817121408353,
         -0.45638820563682087, -0.368021526801695], [0.5443411818155726,                                
         0.3060130876613273, 0.371948185450681]] 
