configs:
    - configs/datasets/ref_real/ref_real.yaml

dataloader_cfg:
    dataset_cfg: &dataset_cfg
        ratio: 0.75
        data_root: data/datasets/renders_gtnormals/shiny_kitchen/train
        view_sample: [0, null, 1]

val_dataloader_cfg:
    dataset_cfg:
        ratio: 0.75
        data_root: data/datasets/renders_gtnormals/shiny_kitchen/test
        view_sample: [0, null, 1]

model_cfg:
    sampler_cfg:
        preload_gs: data/datasets/renders_gtnormals/shiny_kitchen/train/sparse/0/points3D_dense.ply
        spatial_scale: 0.8675505223184453
        # Environment Gaussian
        env_preload_gs: data/datasets/renders_gtnormals/shiny_kitchen/train/envs/points3D.ply
        # env_bounds: [[-30.0, -30.0, -30.0], [30.0, 30.0, 30.0]]
        env_bounds: [[-1.0615542659804156, -0.6039520647556317, -0.3538638054347511], 
         [0.6747792144581365, 0.16631975057342768, 0.42812799100110493]] 
